---
- name: Deploy Python Application from GitHub to EC2 via Apache
  hosts: webservers
  become: yes

  vars:
    app_repo: "https://github.com/chsagar001/AnsibleDeployment.git"
    app_dest: "/var/www/html/myapp"
    apache_site_conf: "/etc/apache2/sites-available/myapp.conf"
    venv_path: "{{ app_dest }}/venv"

  tasks:
    - name: Install required system packages
      apt:
        name:
          - apache2
          - git
          - python3
          - python3-pip
          - python3-venv
          - libapache2-mod-wsgi-py3
        state: present
        update_cache: yes

    - name: Ensure app directory exists
      file:
        path: "{{ app_dest }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Mark the app directory as safe for git
      command: git config --global --add safe.directory {{ app_dest }}

    - name: Clone the GitHub repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dest }}"
        version: HEAD
        force: yes

    - name: Set correct permissions for app folder
      file:
        path: "{{ app_dest }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Create a Python virtual environment
      command: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}"

    - name: Install Python dependencies inside virtualenv
      command: "{{ venv_path }}/bin/pip install -r {{ app_dest }}/requirements.txt"

    - name: Create WSGI entrypoint
      copy:
        dest: "{{ app_dest }}/app.wsgi"
        content: |
          import sys
          import os
          sys.path.insert(0, '{{ app_dest }}/Backend')
          activate_this = os.path.join('{{ venv_path }}', 'bin', 'activate_this.py')
          if os.path.exists(activate_this):
              with open(activate_this) as file_:
                  exec(file_.read(), dict(__file__=activate_this))
          from backend import app as application

    - name: Create Apache site config
      copy:
        dest: "{{ apache_site_conf }}"
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@localhost
              DocumentRoot {{ app_dest }}

              WSGIDaemonProcess myapp python-home={{ venv_path }} python-path={{ app_dest }}/Backend
              WSGIProcessGroup myapp
              WSGIScriptAlias / {{ app_dest }}/app.wsgi

              <Directory {{ app_dest }}>
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: Enable custom Apache site
      command: "a2ensite myapp.conf"
      notify: Restart Apache

    - name: Enable WSGI module using a2enmod
      command: "a2enmod wsgi"
      notify: Restart Apache

    - name: Disable default Apache site
      command: "a2dissite 000-default.conf"
      ignore_errors: yes
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
        