- name: Deploy FastAPI App Behind Apache
  hosts: webservers
  become: yes

  vars:
    app_dir: /var/www/html/fastapiapp
    repo_url: https://github.com/chsagar001/AWSAutomation.git
    apache_site_conf_path: /etc/apache2/sites-available/fastapiapp.conf
    apache_index_path: /var/www/html/index.html

  tasks:
    - name: Install Apache2 and git
      apt:
        name:
          - apache2
          - git
        state: present
        update_cache: yes

    - name: Enable Apache proxy modules
      apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - proxy
        - proxy_http

    - name: Clone FastAPI app repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: HEAD
        force: yes
    - name: Deploy Apache site configuration
      copy:
        dest: "{{ apache_site_conf_path }}"
        content: |
          <VirtualHost *:80>
              ServerName 3.227.19.34

              DocumentRoot /var/www/html

              <Directory /var/www/html>
                  Options Indexes FollowSymLinks
                  AllowOverride None
                  Require all granted
              </Directory>
              ErrorLog ${APACHE_LOG_DIR}/fastapi_error.log
              CustomLog ${APACHE_LOG_DIR}/fastapi_access.log combined
          </VirtualHost>
        owner: root
        group: root
        mode: '0644'

    - name: Enable fastapiapp Apache site
      command: a2ensite fastapiapp.conf
      args:
        creates: /etc/apache2/sites-enabled/fastapiapp.conf

    - name: Disable default Apache site
      command: a2dissite 000-default.conf
      ignore_errors: yes

    - name: Reload Apache to apply changes
      service:
        name: apache2
        state: reloaded
