---
- name: Deploy FastAPI App Behind Apache
  hosts: webservers
  become: yes

  vars:
    app_dir: /var/www/html/fastapiapp
    repo_url: https://github.com/chsagar001/AWSAutomation.git

  tasks:

    - name: Ensure required packages are installed
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - git
          - apache2
        state: present
        update_cache: yes

    - name: Clone FastAPI app repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: HEAD

    - name: Create Python virtual environment
      command: python3 -m venv venv
      args:
        chdir: "{{ app_dir }}"
        creates: "{{ app_dir }}/venv"

    - name: Install Python dependencies (FastAPI, Uvicorn, Gunicorn)
      pip:
        virtualenv: "{{ app_dir }}/venv"
        name:
          - fastapi
          - "uvicorn[standard]"
          - gunicorn

    - name: Create systemd service for FastAPI
      copy:
        dest: /etc/systemd/system/fastapi.service
        content: |
          [Unit]
          Description=Gunicorn instance to serve FastAPI app
          After=network.target

          [Service]
          User=www-data
          Group=www-data
          WorkingDirectory={{ app_dir }}
          Environment="PATH={{ app_dir }}/venv/bin"
          ExecStart={{ app_dir }}/venv/bin/gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 127.0.0.1:8000

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start FastAPI service
      systemd:
        daemon_reload: yes
        name: fastapi
        state: started
        enabled: yes

    - name: "Enable Apache proxy module: proxy"
      command: a2enmod proxy
      notify: Restart Apache

    - name: "Enable Apache proxy module: proxy_http"
      command: a2enmod proxy_http
      notify: Restart Apache

    - name: Configure Apache to reverse proxy FastAPI
      copy:
        dest: /etc/apache2/sites-available/fastapi.conf
        content: |
          <VirtualHost *:80>
              ServerName 3.227.19.34

              ProxyPreserveHost On
              ProxyPass / http://127.0.0.1:8000/
              ProxyPassReverse / http://127.0.0.1:8000/

              ErrorLog ${APACHE_LOG_DIR}/fastapi_error.log
              CustomLog ${APACHE_LOG_DIR}/fastapi_access.log combined
          </VirtualHost>

    - name: Enable fastapi site
      command: a2ensite fastapi.conf
      args:
        creates: /etc/apache2/sites-enabled/fastapi.conf
      notify: Restart Apache

    - name: Disable default Apache site
      command: a2dissite 000-default.conf
      ignore_errors: yes
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
