---
- name: Launch EC2 Instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2
      amazon.aws.ec2_instance:
        name: AWXApp
        key_name: awx-key
        instance_type: t2.micro
        image_id: ami-020cba7c55df1f615
        region: us-east-1
        wait: yes
        count: 1
      register: ec2_output

    - name: Show public IP
      debug:
        var: ec2_output.instances[0].public_ip_address