---
- name: Install Apache
  hosts: ip-172-31-2-69.ec2.internal
  become: true
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes